// apps/web/scripts/build.ts — the single `bun build` driver (01-architecture-layout.md §4,
// 02-architecture-layout-and-package-build.md §8).
//
// Invoked by the Docker build stage and by `bun run build`. It:
//   0. Compiles the workspace package graph (core → renderer → web-data) from the repository root
//      BEFORE any client/server bundle. `Bun.build` resolves the app's `@pulse/web-data/*` imports
//      through the package `exports` map (→ dist/*) and does NOT compile workspace deps from source,
//      so the package dist must exist first. A package compile failure exits non-zero and publishes
//      no new client/server bundle or manifest (02 §8).
//   1. Generates src/version.ts from the release version (arg/env, default the "0.0.0-dev"
//      sentinel), following apps/cli/src/version.ts: a build-time constant, never read from
//      package.json at runtime, deterministic (the version literal is the only variable).
//   2. Calls buildClient (dist/client, content-hashed, minified, sourcemap=linked) — the SPA bundle.
//      buildClient copies src/client/index.html and publishes manifest.json atomically.
//   3. Bundles src/server/index.ts → dist/server/ (target: bun) — the server entry (dist/server/index.js).

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { buildClient } from "./build-client.js";
import type { ClientBuildOptions, ClientBuildResult } from "./build-client.js";

const SCRIPTS_DIR = import.meta.dir;
const APP_ROOT = resolve(SCRIPTS_DIR, "..");
const SRC_DIR = resolve(APP_ROOT, "src");
const DIST_DIR = resolve(APP_ROOT, "dist");

/** Repository root — two levels up from `apps/web`. The package graph is compiled from here so the
 *  relative `packages/web-data` project path resolves. */
export const REPO_ROOT = resolve(APP_ROOT, "..", "..");

/** The committed version sentinel a local (non-release) build carries. */
export const VERSION_SENTINEL = "0.0.0-dev";

/** apps/web/src/version.ts — the single source of the baked web-app version. */
const VERSION_FILE = resolve(SRC_DIR, "version.ts");

/**
 * Render the exact bytes of `version.ts` for a given version. Pure and deterministic — the ONLY
 * variable is the version literal (emitted via `JSON.stringify`, so it is always a valid,
 * correctly-escaped string). No clock/host/pid/random content; calling it twice with the same
 * version yields byte-identical output.
 */
export function renderVersionModule(version: string): string {
  return [
    "// apps/web/src/version.ts — the web-app version string.",
    "//",
    "// GENERATED by apps/web/scripts/build.ts — DO NOT hand-edit. A local (non-release) build keeps the",
    '// "0.0.0-dev" sentinel; the release build regenerates this file with the git tag before bundling.',
    "// Deterministic: the version literal is the only variable, and it is never read from package.json",
    "// at runtime.",
    "",
    '/** The Pulse web-app version, baked at build time. `"0.0.0-dev"` for a local build. */',
    `export const WEB_APP_VERSION = ${JSON.stringify(version)};`,
    "",
  ].join("\n");
}

/** Write `version.ts` for the given version. Overwrites deterministically. */
export function writeVersionFile(version: string, filePath: string = VERSION_FILE): void {
  writeFileSync(filePath, renderVersionModule(version), "utf8");
}

/** Resolve the version to bake: first CLI arg, else `PULSE_BUILD_VERSION`, else `WEB_APP_VERSION`
 *  env override, else the sentinel. */
function resolveVersionArg(): string {
  const arg = process.argv[2];
  if (arg !== undefined && arg.length > 0) return arg;
  const env = process.env.PULSE_BUILD_VERSION;
  if (env !== undefined && env.length > 0) return env;
  const webEnv = process.env.WEB_APP_VERSION;
  if (webEnv !== undefined && webEnv.length > 0) return webEnv;
  return VERSION_SENTINEL;
}

/**
 * Compile the `@pulse/web-data` workspace package graph (core → renderer → web-data) from the
 * repository root, ahead of any client/server bundle. Runs `bunx tsc -b packages/web-data`, whose
 * project references build the whole chain in dependency order and emit each package's `dist/`.
 *
 * `Bun.build` resolves the app's `@pulse/web-data/*` imports through the package `exports` map
 * (→ `dist/*`); it never compiles workspace deps from source, so the package dist must be fresh
 * before bundling. Rejects with a non-zero-exit error on any package compile failure, so the caller
 * publishes no new client/server bundle or manifest (02 §8, §12).
 */
export async function compileWorkspacePackages(repoRoot: string = REPO_ROOT): Promise<void> {
  const proc = Bun.spawn({
    cmd: ["bunx", "tsc", "-b", "packages/web-data"],
    cwd: repoRoot,
    stdout: "inherit",
    stderr: "inherit",
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`apps/web: @pulse/web-data package compile failed (tsc -b exited ${code})`);
  }
}

/**
 * Bundle the server entry `src/server/index.ts` → `dist/server/` (target: bun), keeping the stable
 * `dist/server/index.js` entry the image CMD runs. Throws on a bundle failure.
 */
export async function bundleServer(srcDir: string = SRC_DIR, distDir: string = DIST_DIR): Promise<void> {
  const server = await Bun.build({
    entrypoints: [resolve(srcDir, "server/index.ts")],
    outdir: resolve(distDir, "server"),
    target: "bun",
  });
  if (!server.success) {
    for (const message of server.logs) console.error(message);
    throw new Error("apps/web: server bundle failed");
  }
}

/**
 * Injectable seams for {@link runBuild}. Production defaults compile the package graph and run the
 * real bundlers; tests inject spies to assert step ordering and compile-failure publication safety
 * without a full bundle.
 */
export interface RunBuildDeps {
  /** Compile the workspace package graph before bundling. Defaults to {@link compileWorkspacePackages}. */
  readonly compilePackages?: (repoRoot: string) => Promise<void>;
  /** Stamp `src/version.ts`. Defaults to {@link writeVersionFile}. */
  readonly writeVersion?: (version: string) => void;
  /** Client bundler. Defaults to {@link buildClient}. */
  readonly buildClientImpl?: (opts: ClientBuildOptions) => Promise<ClientBuildResult>;
  /** Server bundler. Defaults to {@link bundleServer}. */
  readonly bundleServerImpl?: (srcDir: string, distDir: string) => Promise<void>;
  /** Repo root passed to `compilePackages`. Defaults to {@link REPO_ROOT}. */
  readonly repoRoot?: string;
  /** App dist dir the client/server bundles publish into. Defaults to {@link DIST_DIR}. */
  readonly distDir?: string;
}

/**
 * Compile the package graph, regenerate version.ts, run buildClient into dist/client (which copies
 * index.html and writes manifest.json atomically), then bundle the server. The package compile runs
 * FIRST, so a package compile failure throws before version.ts is stamped and before any client
 * manifest or server bundle is published (02 §8).
 */
export async function runBuild(
  version: string = resolveVersionArg(),
  deps: RunBuildDeps = {},
): Promise<void> {
  const compilePackages = deps.compilePackages ?? compileWorkspacePackages;
  const writeVersion = deps.writeVersion ?? writeVersionFile;
  const buildClientImpl = deps.buildClientImpl ?? buildClient;
  const bundleServerImpl = deps.bundleServerImpl ?? bundleServer;
  const repoRoot = deps.repoRoot ?? REPO_ROOT;
  const distDir = deps.distDir ?? DIST_DIR;

  // 0. Compile core → renderer → web-data first. A package compile failure publishes nothing below.
  await compilePackages(repoRoot);

  // 1. Stamp the build version.
  writeVersion(version);

  // 2. Client bundle — content-hashed asset names, sourcemap=linked, manifest published atomically.
  const client = await buildClientImpl({
    outdir: resolve(distDir, "client"),
    minify: true,
    sourcemap: "linked",
    clean: true,
  });
  if (!client.ok) {
    for (const message of client.errors) console.error(message);
    throw new Error("apps/web: client bundle failed");
  }

  // 3. Server entry — target: bun, stable dist/server/index.js.
  await bundleServerImpl(SRC_DIR, distDir);
}

if (import.meta.main) await runBuild();
