// apps/web/src/version.ts — the web-app version string.
//
// GENERATED by apps/web/scripts/build.ts — DO NOT hand-edit. A local (non-release) build keeps the
// "0.0.0-dev" sentinel; the release build regenerates this file with the git tag before bundling.
// Deterministic: the version literal is the only variable, and it is never read from package.json
// at runtime.

/** The Pulse web-app version, baked at build time. `"0.0.0-dev"` for a local build. */
export const WEB_APP_VERSION = "0.0.0-dev";
