/**
 * The curated icon set: every icon deck renders, keyed by the string token that
 * estate config, `registerPage` and feature state maps use.
 *
 * Import each Lucide icon by name here and nowhere else. Never use
 * `lucide-react/dynamic` or a namespace import: either one ships the whole set.
 *
 * Aliases (`check-circle` ≡ `circle-check`, Lucide's older names, and the
 * literal unicode glyphs legacy state maps still use) resolve to the same
 * component, so existing tokens keep working while features migrate.
 */
import {
  Activity,
  Archive,
  Ban,
  BookOpen,
  Boxes,
  CalendarClock,
  ChartPie,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDashed,
  CircleMinus,
  CirclePlay,
  CirclePlus,
  CircleQuestionMark,
  CircleSlash,
  CircleStop,
  CircleX,
  ClockAlert,
  CloudOff,
  Contrast,
  Copy,
  DatabaseCheck,
  DatabaseX,
  Diamond,
  ExternalLink,
  EyeOff,
  File,
  FileCog,
  FileDigit,
  FileQuestionMark,
  Folder,
  FolderOpen,
  Gauge,
  GitCompareArrows,
  Hourglass,
  House,
  Inbox,
  Info,
  LayoutGrid,
  Link,
  Link2Off,
  Minus,
  Monitor,
  Moon,
  OctagonAlert,
  Play,
  RefreshCw,
  Search,
  SearchX,
  Server,
  Slash,
  Sun,
  SunMoon,
  Triangle,
  TriangleAlert,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
// pulse additions: the shell and pulse views' icons deck's set lacks.
import {
  Bell,
  ChevronLeft,
  ChevronUp,
  CircleAlert,
  Clock,
  Command,
  Keyboard,
  List,
  Loader,
  Maximize,
  Menu,
  Network,
  PanelRight,
  TrendingUp,
  Wifi,
  WifiOff,
} from "lucide-react";

export const ICONS = {
  // Status.
  "circle-check": CircleCheck,
  "check-circle": CircleCheck,
  "database-check": DatabaseCheck,
  "circle-x": CircleX,
  "x-circle": CircleX,
  "circle-minus": CircleMinus,
  "minus-circle": CircleMinus,
  minus: Minus,
  "circle-help": CircleQuestionMark,
  "circle-question-mark": CircleQuestionMark,
  slash: Slash,
  "circle-slash": CircleSlash,
  "circle-stop": CircleStop,
  "circle-dashed": CircleDashed,
  "triangle-alert": TriangleAlert,
  "alert-triangle": TriangleAlert,
  "octagon-alert": OctagonAlert,
  "alert-octagon": OctagonAlert,
  "clock-alert": ClockAlert,
  hourglass: Hourglass,
  "calendar-clock": CalendarClock,
  ban: Ban,
  info: Info,
  circle: Circle,

  // Objects and actions.
  inbox: Inbox,
  "database-off": DatabaseX,
  "database-x": DatabaseX,
  "cloud-off": CloudOff,
  link: Link,
  "link-off": Link2Off,
  unlink: Link2Off,
  file: File,
  "file-digit": FileDigit,
  "file-binary": FileDigit,
  "file-question": FileQuestionMark,
  "file-question-mark": FileQuestionMark,
  folder: Folder,
  "folder-open": FolderOpen,
  "external-link": ExternalLink,
  "search-x": SearchX,
  play: Play,
  "circle-play": CirclePlay,
  "play-circle": CirclePlay,
  archive: Archive,
  "eye-off": EyeOff,
  x: X,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  copy: Copy,
  check: Check,
  "refresh-cw": RefreshCw,

  // Navigation (page registrations and the shell).
  "layout-grid": LayoutGrid,
  server: Server,
  boxes: Boxes,
  "git-compare": GitCompareArrows,
  activity: Activity,
  zap: Zap,
  "book-open": BookOpen,
  "file-cog": FileCog,
  house: House,
  monitor: Monitor,
  gauge: Gauge,

  // Theme.
  sun: Sun,
  moon: Moon,
  "sun-moon": SunMoon,

  // Filtering and search.
  search: Search,
  "circle-plus": CirclePlus,
  "plus-circle": CirclePlus,

  // Legacy unicode glyphs from pre-migration state maps.
  "✓": Check,
  "✕": X,
  "▲": Triangle,
  "⚠": TriangleAlert,
  "◆": Diamond,
  "○": Circle,
  "◐": Contrast,
  "◔": ChartPie,
  "∅": Ban,
  ℹ: Info,
  "☀": Sun,
  "☾": Moon,

  // pulse additions.
  bell: Bell,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "circle-alert": CircleAlert,
  clock: Clock,
  command: Command,
  keyboard: Keyboard,
  list: List,
  loader: Loader,
  maximize: Maximize,
  menu: Menu,
  network: Network,
  "panel-right": PanelRight,
  "trending-up": TrendingUp,
  triangle: Triangle,
  wifi: Wifi,
  "wifi-off": WifiOff,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

/** The neutral glyph rendered for an unknown token (e.g. a typo in estate config). */
export const FALLBACK_ICON: LucideIcon = Circle;

export function isIconName(name: string): name is IconName {
  return Object.hasOwn(ICONS, name);
}
