// apps/cli/src/version.ts — the CLI version string (00 §5, REQ-CLI-06).
//
// GENERATED by apps/cli/scripts/build-bin.ts — DO NOT hand-edit. A local (non-release) build
// keeps the "0.0.0-dev" sentinel; the release build regenerates this file with the git tag
// before `bun build --compile`. Deterministic: the version literal is the only variable, and
// it is never read from package.json at runtime (a --compile binary cannot rely on it).

/** The Pulse CLI version, baked at build time. `"0.0.0-dev"` for a local build. */
export const PULSE_VERSION = "0.0.0-dev";
