// agent-kit/src/emit/claude.ts
// The Claude Code emitter (REQ-ECO-01/02, REQ-SKILL-06).
//
// The reference ecosystem (live eval, REQ-EVAL-03). Runnable: skills become
// `.claude/skills/<id>/SKILL.md` with YAML frontmatter, subagents become `.claude/agents/<id>.md`,
// guidance becomes `CLAUDE.md` (root primer) + `.claude/docs/<id>.md`.

import type { Emitter, EmittedFile, Manifest, Slots, ContentUnit } from "./types.js";
import { ContentValidationError } from "./errors.js";
import { renderSections } from "./markdown.js";
import { renderFrontmatter } from "./frontmatter.js";

/** The id of the guidance unit that becomes the root `CLAUDE.md` primer (manifest order). */
const ROOT_PRIMER_ID = "vocab-primer";

/** Banner stamped atop every generated Claude file (single-source provenance, REQ-DRIFT-01). */
const BANNER =
  "<!-- GENERATED by @pulse/agent-kit — DO NOT hand-edit. " +
  "Source: agent-kit/src/content/**. Regenerate: bun run --filter @pulse/agent-kit generate -->\n";

/**
 * Assert a unit is well-formed for the Claude emitter: non-empty rendered body. A malformed
 * unit throws `ContentValidationError` — no degraded emission.
 */
function requireBody(unit: ContentUnit, body: string): void {
  if (body.trim().length === 0) {
    throw new ContentValidationError(unit.id, "rendered body is empty");
  }
}

/** Emit one guidance unit: the root primer → `CLAUDE.md`; every other → `.claude/docs/<id>.md`. */
function emitGuidance(unit: ContentUnit, slots: Slots): EmittedFile {
  const body = renderSections(unit.render(slots));
  requireBody(unit, body);
  const path = unit.id === ROOT_PRIMER_ID ? "CLAUDE.md" : `.claude/docs/${unit.id}.md`;
  return { path, contents: `${BANNER}\n# ${unit.frontmatter.name}\n\n${body}` };
}

/** Emit one skill unit as a runnable `.claude/skills/<id>/SKILL.md` with YAML frontmatter. */
function emitSkill(unit: ContentUnit, slots: Slots): EmittedFile {
  const body = renderSections(unit.render(slots));
  requireBody(unit, body);
  const contents = `${renderFrontmatter(unit.frontmatter)}\n${BANNER}\n${body}`;
  return { path: `.claude/skills/${unit.id}/SKILL.md`, contents };
}

/** Emit one subagent unit as `.claude/agents/<id>.md` with `name`/`description` frontmatter. */
function emitSubagent(unit: ContentUnit, slots: Slots): EmittedFile {
  const body = renderSections(unit.render(slots));
  requireBody(unit, body);
  // Subagents carry no argument-hint; renderFrontmatter omits it when undefined.
  const fm = { name: unit.frontmatter.name, description: unit.frontmatter.description };
  const contents = `${renderFrontmatter(fm)}\n${BANNER}\n${body}`;
  return { path: `.claude/agents/${unit.id}.md`, contents };
}

/**
 * The Claude Code emitter. Pure and deterministic: identical `(manifest, slots)`
 * yields byte-identical `EmittedFile[]`, ordered by `manifest.units`. Skips units that do
 * not target `"claude"`. Throws `ContentValidationError` on a malformed unit; an
 * unrecognized `kind` is unreachable given the `ContentKind` union but is guarded.
 */
export const claudeEmitter: Emitter = {
  ecosystem: "claude",
  emit(manifest: Manifest, slots: Slots): EmittedFile[] {
    const files: EmittedFile[] = [];
    for (const unit of manifest.units) {
      if (!unit.targets.includes("claude")) continue;
      switch (unit.kind) {
        case "guidance": files.push(emitGuidance(unit, slots)); break;
        case "skill": files.push(emitSkill(unit, slots)); break;
        case "subagent": files.push(emitSubagent(unit, slots)); break;
        default: {
          // Exhaustiveness guard — `kind` is a closed union.
          const _never: never = unit.kind;
          throw new ContentValidationError(unit.id, `unknown content kind '${_never}'`);
        }
      }
    }
    return files;
  },
};
