// agent-kit/src/emit/codex.ts
// The Codex emitter (REQ-ECO-02).
//
// Codex has NO skill runtime, so skills degrade to instruction playbooks and subagents fold into
// instruction prose. Layout: one `AGENTS.md` (all guidance + a "Playbooks" index) plus
// `skills/NN-<id>.md` playbooks (a stable two-digit ordinal by manifest position).

import type { Emitter, EmittedFile, Manifest, Slots, ContentUnit } from "./types.js";
import { ContentValidationError } from "./errors.js";
import { renderSections } from "./markdown.js";

const BANNER =
  "<!-- GENERATED by @pulse/agent-kit — DO NOT hand-edit. Source: agent-kit/src/content/**. " +
  "Regenerate: bun run --filter @pulse/agent-kit generate -->\n";

/** Two-digit, 1-based ordinal for a playbook file stem, from its manifest position. */
function ordinal(index: number): string {
  return String(index + 1).padStart(2, "0");
}

/** Render one unit's body, asserting non-empty (throws `ContentValidationError`). */
function body(unit: ContentUnit, slots: Slots): string {
  const b = renderSections(unit.render(slots));
  if (b.trim().length === 0) throw new ContentValidationError(unit.id, "rendered body is empty");
  return b;
}

/**
 * The Codex emitter. Produces `AGENTS.md` (guidance + a playbook index) and one
 * `skills/NN-<id>.md` per skill/subagent unit (instruction prose — no runtime). Pure and
 * deterministic; skips units not targeting `"codex"`.
 */
export const codexEmitter: Emitter = {
  ecosystem: "codex",
  emit(manifest: Manifest, slots: Slots): EmittedFile[] {
    const targeted = manifest.units.filter((u) => u.targets.includes("codex"));
    const files: EmittedFile[] = [];
    const playbookLinks: string[] = [];

    // Instruction playbooks for every skill/subagent unit, ordered by manifest position.
    targeted.forEach((unit, i) => {
      if (unit.kind === "guidance") return;
      const stem = `${ordinal(i)}-${unit.id}`;
      const path = `skills/${stem}.md`;
      files.push({
        path,
        contents: `${BANNER}\n# ${unit.frontmatter.name}\n\n> ${unit.frontmatter.description}\n\n${body(unit, slots)}`,
      });
      playbookLinks.push(`- [${unit.frontmatter.name}](./${path}) — ${unit.frontmatter.description}`);
    });

    // AGENTS.md: all guidance units, then the playbook index.
    const guidanceSections = targeted
      .filter((u) => u.kind === "guidance")
      .map((u) => `## ${u.frontmatter.name}\n\n${body(u, slots)}`)
      .join("\n\n");
    const index = playbookLinks.length > 0
      ? `\n\n## Playbooks\n\nDelegated instruction playbooks (Codex has no skill runtime):\n\n${playbookLinks.join("\n")}\n`
      : "\n";
    files.unshift({
      path: "AGENTS.md",
      contents: `${BANNER}\n# Pulse — agent operating guide\n\n${guidanceSections}${index}`,
    });
    return files;
  },
};
