// agent-kit/src/emit/generic.ts
// The generic emitter (REQ-ECO-03).
//
// Best-effort, UNTESTED `AGENTS.md`-class output for non-first-class agents. Every unit
// (guidance, skill, subagent) folds into a single `AGENTS.md`; it is emitted but the pack never
// claims tested support for it. `"generic"` is excluded from `FIRST_CLASS_ECOSYSTEMS`, so no
// contract/eval suite gates it.

import type { Emitter, EmittedFile, Manifest, Slots } from "./types.js";
import { ContentValidationError } from "./errors.js";
import { renderSections } from "./markdown.js";

const BANNER =
  "<!-- GENERATED by @pulse/agent-kit — DO NOT hand-edit. Source: agent-kit/src/content/**. " +
  "Regenerate: bun run --filter @pulse/agent-kit generate -->\n";
const DISCLAIMER =
  "> Best-effort generic guidance. Claude Code, Codex, and Pi are the tested first-class " +
  "ecosystems; this file is provided as-is for other agents.\n";

/**
 * The generic emitter. Folds ALL targeted units (any kind) into one `AGENTS.md`, ordered
 * by `manifest.units`. Best-effort and untested (REQ-ECO-03). Pure and deterministic.
 */
export const genericEmitter: Emitter = {
  ecosystem: "generic",
  emit(manifest: Manifest, slots: Slots): EmittedFile[] {
    const sections = manifest.units
      .filter((u) => u.targets.includes("generic"))
      .map((u) => {
        const b = renderSections(u.render(slots));
        if (b.trim().length === 0) throw new ContentValidationError(u.id, "rendered body is empty");
        return `## ${u.frontmatter.name}\n\n${b}`;
      })
      .join("\n\n");
    return [{
      path: "AGENTS.md",
      contents: `${BANNER}${DISCLAIMER}\n# Pulse — agent operating guide (generic)\n\n${sections}\n`,
    }];
  },
};
