// agent-kit/src/emit/pack.ts
// Pack assembly (REQ-GUIDE-01).
//
// Exposes the public `buildGuidancePack()` and the generator hook
// `renderPackModule()` that writes `generated/guidance-pack.generated.ts` (the committed
// GUIDANCE_PACK + PACK_BYTES module). Every scaffolded file is `merge: "create-only"`
// (CREATE_ONLY, REQ-GUIDE-06 / REQ-SEC-03).
//
// The pack is assembled from the committed `generated/**` trees (not re-emitted), so the pack
// ships exactly the reviewed bytes. Only the FIRST_CLASS ecosystems' trees are packed;
// `generic/` is emitted but not part of the scaffolded pack (REQ-ECO-03).

import { readFile, readdir } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import type { GuidancePack, GuidancePackFile } from "@pulse/renderer";
import { CREATE_ONLY, FIRST_CLASS_ECOSYSTEMS } from "./types.js";

/** Stable pack id consumed by the CLI init-seam. */
const PACK_ID = "agent-kit";

/** Absolute path to `agent-kit/generated` (default; overridable for the generator temp dir). */
const GENERATED_ROOT = resolve(import.meta.dir, "../../generated");

/** Recursively list files under `dir` as sorted `dir`-relative paths (stable order). */
async function listFiles(dir: string): Promise<string[]> {
  const out: string[] = [];
  async function walk(d: string): Promise<void> {
    for (const entry of await readdir(d, { withFileTypes: true })) {
      const abs = join(d, entry.name);
      if (entry.isDirectory()) await walk(abs);
      else out.push(relative(dir, abs));
    }
  }
  await walk(dir);
  return out.sort();
}

/**
 * Build the guidance pack the CLI scaffolds (REQ-GUIDE-01). Assembles `GuidancePackFile`
 * entries from the committed first-class `generated/**` trees; every entry is create-only
 * (REQ-GUIDE-06). `source` is the pack-internal key (`<ecosystem>/<path>`), `target` is the
 * consumer-repo destination (same relative path). Reads the committed tree — never re-emits.
 *
 * @param root - the generated root (defaults to `agent-kit/generated`)
 * @returns a `GuidancePack` value (type consumed from `@pulse/renderer`)
 */
export async function buildGuidancePack(root: string = GENERATED_ROOT): Promise<GuidancePack> {
  const files: GuidancePackFile[] = [];
  for (const ecosystem of FIRST_CLASS_ECOSYSTEMS) {
    const dir = join(root, ecosystem);
    for (const rel of await listFiles(dir)) {
      const key = `${ecosystem}/${rel}`; // pack-internal source key
      files.push({ source: key, target: key, merge: CREATE_ONLY });
    }
  }
  // Stable order: FIRST_CLASS_ECOSYSTEMS order, then sorted paths within each.
  return { id: PACK_ID, files };
}

/**
 * Read every packed file's bytes into the `source → contents` map backing `readPackSource`
 * at release build (PACK_BYTES). Keys match `GuidancePackFile.source` exactly.
 */
async function readPackBytes(root: string): Promise<Record<string, string>> {
  const pack = await buildGuidancePack(root);
  const bytes: Record<string, string> = {};
  for (const f of pack.files) bytes[f.source] = await readFile(join(root, f.source), "utf8");
  return bytes;
}

/**
 * Render the committed `generated/guidance-pack.generated.ts` data module.
 * Deterministic: keys are emitted in sorted order and every value goes through
 * `JSON.stringify` (correct escaping, stable) — the `renderVersionModule` discipline
 * (apps/cli/scripts/build-bin.ts). Called by `scripts/generate.ts`.
 *
 * @param root - the generated root the pack is assembled from
 * @returns the exact TypeScript source of the data module
 */
export async function renderPackModule(root: string): Promise<string> {
  const pack = await buildGuidancePack(root);
  const bytes = await readPackBytes(root);
  const fileEntries = pack.files
    .map(
      (f) =>
        `  { source: ${JSON.stringify(f.source)}, target: ${JSON.stringify(f.target)}, merge: ${JSON.stringify(f.merge)} },`,
    )
    .join("\n");
  const byteEntries = Object.keys(bytes)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(bytes[k])},`)
    .join("\n");

  return [
    "// agent-kit/generated/guidance-pack.generated.ts",
    "//",
    "// GENERATED by @pulse/agent-kit scripts/generate.ts — DO NOT hand-edit.",
    "// Regenerate: bun run --filter @pulse/agent-kit generate. The release build imports",
    "// GUIDANCE_PACK / PACK_BYTES to embed the pack in the CLI binary.",
    "",
    'import type { GuidancePack } from "@pulse/renderer";',
    "",
    "/** The pack the CLI scaffolds; `files[].source` keys index `PACK_BYTES`. */",
    `export const GUIDANCE_PACK: GuidancePack = {`,
    `  id: ${JSON.stringify(pack.id)},`,
    "  files: [",
    fileEntries,
    "  ],",
    "};",
    "",
    "/** Maps each `GuidancePackFile.source` to its literal file contents (create-only text). */",
    "export const PACK_BYTES: Record<string, string> = {",
    byteEntries,
    "};",
    "",
  ].join("\n");
}
