// agent-kit/src/emit/pi.ts
// The Pi emitter (REQ-ECO-01/02, REQ-SKILL-06).
//
// Runnable, like Claude: Pi carries native skill and subagent formats. The STRATEGY is fixed
// (guidance → Pi-native guidance file(s); skill → Pi-native skill; subagent → Pi-native
// subagent); the concrete filenames and frontmatter keys are the OT-01 provisional mapping —
// only these constants + path builders change if Pi's live format differs.

import type { Emitter, EmittedFile, Manifest, Slots, ContentUnit } from "./types.js";
import { ContentValidationError } from "./errors.js";
import { renderSections } from "./markdown.js";
import { renderFrontmatter } from "./frontmatter.js";

const BANNER =
  "<!-- GENERATED by @pulse/agent-kit — DO NOT hand-edit. Source: agent-kit/src/content/**. " +
  "Regenerate: bun run --filter @pulse/agent-kit generate -->\n";

/**
 * Pi-native directory conventions. These are the OT-01 provisional mapping; only the
 * concrete path segments and the frontmatter key spelling may change — the routing by
 * `ContentKind` and the runnable-skill guarantee (REQ-SKILL-06) do not.
 *
 * NOTE: this OT-01 mapping has not been confirmed against a live Pi runtime. If Pi's native
 * skill/subagent layout differs, adjust ONLY these constants + the path builders below.
 */
const PI_GUIDANCE_DIR = ".pi/guidance";
const PI_SKILL_DIR = ".pi/skills";
const PI_AGENT_DIR = ".pi/agents";

function body(unit: ContentUnit, slots: Slots): string {
  const b = renderSections(unit.render(slots));
  if (b.trim().length === 0) throw new ContentValidationError(unit.id, "rendered body is empty");
  return b;
}

/**
 * The Pi emitter. Runnable skills + subagents in Pi-native form; guidance as Pi-native
 * guidance files. Pure and deterministic; skips units not targeting `"pi"`.
 */
export const piEmitter: Emitter = {
  ecosystem: "pi",
  emit(manifest: Manifest, slots: Slots): EmittedFile[] {
    const files: EmittedFile[] = [];
    for (const unit of manifest.units) {
      if (!unit.targets.includes("pi")) continue;
      const b = body(unit, slots);
      switch (unit.kind) {
        case "guidance":
          files.push({ path: `${PI_GUIDANCE_DIR}/${unit.id}.md`,
            contents: `${BANNER}\n# ${unit.frontmatter.name}\n\n${b}` });
          break;
        case "skill":
          files.push({ path: `${PI_SKILL_DIR}/${unit.id}.md`,
            contents: `${renderFrontmatter(unit.frontmatter)}\n${BANNER}\n${b}` });
          break;
        case "subagent": {
          const fm = { name: unit.frontmatter.name, description: unit.frontmatter.description };
          files.push({ path: `${PI_AGENT_DIR}/${unit.id}.md`,
            contents: `${renderFrontmatter(fm)}\n${BANNER}\n${b}` });
          break;
        }
        default: {
          const _never: never = unit.kind;
          throw new ContentValidationError(unit.id, `unknown content kind '${_never}'`);
        }
      }
    }
    return files;
  },
};
